# Generated by Django 3.0.4 on 2020-03-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100, null=True)),
                ('opf', models.CharField(max_length=5)),
                ('inn', models.CharField(max_length=12)),
                ('ogrn', models.CharField(max_length=15)),
                ('kpp', models.CharField(max_length=9, null=True)),
                ('address', models.CharField(max_length=100)),
                ('address_postal', models.CharField(max_length=100)),
                ('address_fact', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=11)),
                ('okved2', models.CharField(max_length=50)),
                ('contract_date', models.CharField(max_length=10)),
                ('begin_date', models.CharField(max_length=10)),
                ('client_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Form_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Формы обучения',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_1', models.CharField(max_length=50, verbose_name='Должность в именит.падеже')),
                ('position_2', models.CharField(max_length=50, verbose_name='Должность в родит.падеже')),
                ('position_3', models.CharField(max_length=50, verbose_name='Должность в дат.падеже')),
                ('position_4', models.CharField(max_length=50, verbose_name='Должность в винит.падеже')),
                ('position_5', models.CharField(max_length=50, verbose_name='Должность в творит.падеже')),
                ('date_approve', models.CharField(max_length=10, verbose_name='Дата утверждения')),
                ('date_exclusion', models.CharField(max_length=10, verbose_name='Дата исключения')),
                ('staff_special', models.CharField(max_length=1, verbose_name='Признак специального должностного лица')),
                ('staff_special_order_date', models.CharField(max_length=10, verbose_name='Дата приказа о назначении специального должностного лица')),
                ('staff_special_order_number', models.CharField(max_length=10, verbose_name='Номер приказа о назначении специального должностного лица')),
                ('client_inn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Clients', verbose_name='Клиент ИНН')),
                ('form_education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Form_education', verbose_name='Форма обучения')),
            ],
            options={
                'verbose_name': 'Штатные расписания',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio1', models.CharField(max_length=100, verbose_name='ФИО в именит падеже')),
                ('fio2', models.CharField(max_length=100, verbose_name='ФИО в родит падеже')),
                ('fio3', models.CharField(max_length=100, verbose_name='ФИО в дат падеже')),
                ('fio4', models.CharField(max_length=100, verbose_name='ФИО в винит падеже')),
                ('fio5', models.CharField(max_length=100, verbose_name='ФИО в творит падеже')),
                ('date_hiring', models.CharField(max_length=10, verbose_name='Дата приема на работу')),
                ('date_firing', models.CharField(max_length=10, verbose_name='Дата увольнения')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Staff')),
            ],
            options={
                'verbose_name': 'Сотрудники',
            },
        ),
    ]
